Refactor scoping code in the SP class
simplesamlphp/simplesamlphp pull request #1653
Opened 2022-06-10 07:46 UTC by Paragin

Make sure the `saml:IDPList` and `IDPList` parameters are not overloaded. From now on, saml:IDPList is being used when SSP is used as a proxy while the IDPList parameter is used when SSP is used as in SP-mode and you want to apply scoping to your AuthnRequest.

See https://github.com/simplesamlphp/simplesamlphp/pull/1563 and  for the full explanation of the changes.

Solves https://github.com/simplesamlphp/simplesamlphp/issues/1562

2022-06-10 15:15 UTC, thijskh requested changes
Great, thanks! It's complex enough to wrap your head around the intended (complex) interactions in the proxy setup but I do think this is now correct and better than it was, and more straightforward.

Great to see that you've added tests! In the ideal world I'd like to see a test that also confirms the ordering as it is now. So that setting it e.g. at runtime overrides idp settings (and not vice versa or merge etc).

One must is that the documentation needs to be updated. Basically grep in docs/ for IDPList. I can do that if desired.

2022-06-10 15:15 UTC, thijskh commented on tests/modules/saml/src/Auth/Source/SPTest.php
> +            );
This can be written as `$this->assertContains('https://scope.example.com', $ar->getIDPList());`

2022-06-10 15:15 UTC, thijskh commented on tests/modules/saml/src/Auth/Source/SPTest.php
> +        );
This can be written as $this->assertContains('https://scope.example.com', $ar->getIDPList());

2022-06-13 07:53 UTC, Paragin commented
@thijskh I've applied your suggestions from the test and added a test that confirms the ordering as well.
If you can do the documentation that would be appreciated. 

I've suggested to apply these changes to the 1.19 branch as well so it can be released sooner. Is that something you are open to?

2022-06-13 08:47 UTC, tvdijen commented
I would be fine with backporting this to 1.19 and tag 1.19.6

2022-06-13 10:01 UTC, thijskh commented
It does change behaviour (for the better I think, but still...). Can we make a more targeted change for 1.19 which adds the ability to set @ runtime without 'improving' the setting behaviour?

2022-06-13 10:01 UTC, merged

2022-06-13 10:17 UTC, tvdijen commented
Ahh, I wasn't aware of that.. In this case it's probably better to not put any more efforts in 1.19

2022-06-13 10:26 UTC, Paragin commented
Ok, then I'll guess we have to wait. 

We have a working workaround so we'll manage, but it's not something I want to keep around for long.. (It involves selectively copy-pasting code from SSA into our own codebase so we manually call the startSSO-function with the right parameters)