SAML: Support for authnContextClassRef in proxy mode
simplesamlphp/simplesamlphp pull request #833
Opened 2018-04-17 10:26 UTC by tauceti2

If SSP works as a proxy, this code retain requested authnContextClassRef from
SP behind the proxy and pass it to the upper IdP. It also pass the
authnContextClassRef sent by the upper IdP back to the SP behind the proxy. By this change SPs behind the proxy can request different authn methods, especially useful for support multi-factor authn.

Please review the code, if it is acceptable also for mode when SSP doesn't work as a proxy.

2018-05-30 17:58 UTC, pradtke commented
We have some proxy use cases where this is undesirable so it would be nice if there was a way to opt in or opt out of the behavior change.  

Use case is that SPs request MFA from the proxy. The proxy performs it own MFA for users and we don't want to request MFA from upstream IdPs.

2018-06-20 13:17 UTC, tauceti2 commented
Hi @pradtke, added configuration option, which can enable that behaviour. By default it is off.

2021-09-20 15:22 UTC, dmotelica requested changes
Hello,
For those who use SimpleSAMLphp as a proxy to delegate l'auhentication to Azure AD and have to be NIH ready (Refeds MFA profile):

File SP.php - add this before line 487 :
--------------------
`if ($state['saml:RequestedAuthnContext']['AuthnContextClassRef'][0]=="https://refeds.org/profile/mfa"){
					$state['saml:RequestedAuthnContext']['AuthnContextClassRef'][0] = 'http://schemas.microsoft.com/claims/multipleauthn';
				}	`

----------------------------------------------------------------

file SAML2.php -  - add this before line 1137:
-----------------------------------------------
`if(isset($state['saml:RequestedAuthnContext']) && $state['saml:sp:AuthnContext']=="http://schemas.microsoft.com/claims/multipleauthn") 
			{
				$state['saml:sp:AuthnContext']="https://refeds.org/profile/mfa";
			}` 

---------------------------------------------------------

in config.php and authsources.php 
------------------------------------
`'proxymode.passAuthnContextClassRef' => true,`

2021-09-20 15:32 UTC, tvdijen commented
Way too specific to add that @dmotelica ..

2021-09-20 15:38 UTC, dmotelica commented on modules/saml/lib/Auth/Source/SP.php
> +                $ar->setRequestedAuthnContext(array(
`if($state['saml:RequestedAuthnContext']['AuthnContextClassRef'][0]=="https://refeds.org/profile/mfa"){
 $state['saml:RequestedAuthnContext']['AuthnContextClassRef'][0] = 
'http://schemas.microsoft.com/claims/multipleauthn'; }`

2021-12-03 14:59 UTC, ghalse commented
This pull request is now referenced from the [REFEDS MFA Profile implementation FAQ](https://wiki.refeds.org/display/PRO/IdP+Product+specific+questions#IdPProductspecificquestions-IrunSimpleSAMLPHPIdP,whattoIneedtodotosupportREFEDSMFAProfile).

For that reason, I wanted to note that since the patch was first written there are changes to SSP that means you need to make sure you include the later merge commits (and particularly [2c6cf5a](https://github.com/simplesamlphp/simplesamlphp/pull/833/commits/2c6cf5a7ed39b6f9270392e9434ccbe1472a37c1)) if you're trying to use this as a patch against recent SSP.

2022-10-26 22:32 UTC, ghalse commented
I've forward ported this for simplesamlphp 2.0.0-rc2, and the patch is in 554466328f388a6bcc686d5ce6df6f607d1a352f

2022-10-27 09:01 UTC, tvdijen commented
I can't seem to cherry-pick that commit.. It's not part of any branch.. What exactly did you do @ghalse ?

2022-10-27 09:18 UTC, ghalse commented
> I can't seem to cherry-pick that commit.. It's not part of any branch.. What exactly did you do @ghalse ?

It's part of the authnContextClassRef branch in ghalse/simplesamlphp, which was based off the simplesamlphp-2.0 branch

https://github.com/simplesamlphp/simplesamlphp/compare/simplesamlphp-2.0...ghalse:simplesamlphp:authnContextClassRef

2022-10-27 09:55 UTC, tvdijen commented
Ah, thanks! Cherry-pick it!

2022-10-27 09:55 UTC, closed without merging